### ISSUE TITLE
Incorporate OAuth client changes

### ISSUE THREAD

**Issue by hburn7** [osu-tournament-rating/otr-processor#26]
Instead of the current way we call the `otr-api`, we need to incorporate the new OAuth changes. 

Depends on:
- [x] https://github.com/osu-tournament-rating/otr-api/pull/110 (see here for changes)
- [x] https://github.com/osu-tournament-rating/otr-web/issues/104
- [x] Task 1 ready in production
- [ ] Privileged OAuth client available in production (@hburn7)

**Comment by 486c** [comment]
Done in #33 and #34
