### ISSUE TITLE
Use new pagination strategy for matches

### ISSUE THREAD

**Issue by hburn7** [osu-tournament-rating/otr-processor#47]
There are plans to rework how we fetch match data. We need to adopt the changes from this issue: https://github.com/osu-tournament-rating/otr-api/issues/308

## Depends on

- [x] https://github.com/osu-tournament-rating/otr-api/issues/308

## Tasks

- [ ] Remove usage of `/matches/convert`
- [ ] Remove usage of `/matches/ids`
- [ ] Remove usage of `/matches/id-mapping`
- [ ] Implement the pagination strategy described in the above linked issue
