### ISSUE TITLE
Rewrite of primary rating calculation function

### ISSUE THREAD

**Issue by hburn7** [osu-tournament-rating/otr-processor#6]
Rewrite of: https://github.com/osu-tournament-rating/otr-data-py/blob/master/src/main.py#L251

This one is complicated. This is the "mother of all" functions in Python. In this project, this function should live in `src/model/model.rs`. A `calc_ratings` function is currently in progress. The idea is to return a `RatingCalculationResult` which contains the base ratings, rating stats, and any rating adjustments that happened during recalculation. `RatingCalculationResult` should also contain any statistics that *cannot be processed after the fact*.

We need to create and calculate `RatingAdjustment`(decay, in this context) objects during the recalculation. We do this in real-time as we are simulating the application of decay in times past as well. This will then affect the ratings that are yet to be processed in the lifetime of the algorithm (this is because we process all matches in order from oldest to newest).

There are a multitude of other statistics the Python version chooses to calculate in real-time that may not need to be, such as average teammate / opponent ratings for a given match. As long as we have a collection of `MatchRatingStats` returned by this function, we should be able to process all other stats after the fact.

Tasks for completion:

- [x] Algorithm successfully processes all ratings across all modes. This is the simplest version of the rating processor, taking initial ratings and returning updated ratings. Every rated game is a free-for-all as far as the algorithm is concerned. This is the `base_ratings` field in `RatingCalculationResult`.
- [x] Include all rating decay adjustments made over the lifetime of the algorithm as part of the `adjustments` field in the result.
- [x] Include all `MatchRatingStats` that must be processed in real-time as we go through the algorithm (`RatingCalculationResult.rating_stats`).

**Comment by hburn7** [comment]
#35 has a good enough implementation of this issue for it to be closed. We need to focus now on getting the remaining statistics populated as well as putting everything into the database. Once this is complete, the app will be at feature parity of the former processor.
