### ISSUE TITLE
Remove historical global rank, country rank, and percentile tracking

### ISSUE THREAD

**Issue by hburn7** [osu-tournament-rating/otr-processor#66]
Most systems do not have full global/country/percentile historical tracking. This can be removed as we only care about rating histories (which are not computationally expensive).

- [ ] Remove rank and percentile tracking from o!TR processor
- [ ] Calculate global ranks, country ranks, and percentile *once* at the end of processing.
- [ ] For each player, store the following in an object: `GlobalRank`, `CountryRank`, `Percentile`
