### ISSUE TITLE
Remove API dependency and use a direct database connection

### ISSUE THREAD

**Issue by myssto** [osu-tournament-rating/otr-processor#68]
We have spent a lot of development time on trying to make sure that the API and processor are on the same page in terms of sending and receiving data between each other. At this point the processor should simply just have it's own connection to the database for data manipulation. As long as we make sure to keep the entity structures in sync which is much easier than what we are currently doing, it should not be an issue.

- [x] Add database connection
  - [x] Modify config to include a connection string
  - [x] Install and configure relevant crates
- [x] Refactor to query the database for data instead of the API
  - [x] Pull matches, games, and scores directly from db
    - [x] Query for matches which have a verification status of 4 and a processing status of 4.'
    - [x] Include games and game scores which have a verification status of 4
    - [x] Move processing status to 5 when processing is complete.
   - [x] Pull players from the database
   - [x] Pull ruleset data from the database
- [x] Refactor logic to use new data structures
  - [x] rating_utils
  - [x] decay
  - [x] otr_model
  - [x] rating_tracker  
  - [x] Remove global / country rank & percentile history tracking functionalities
  - [x] Fix tests
- [x] Remove old structs 
- [x] Ensure `RatingAdjusment` `player_rating_id` values are linked to the `PlayerRating` before insertion
- [x] Refactor to save generated data to the database instead of posting to the API
  - [x] Save `RatingAdjustment`s
- [x] Successful run of the processor
