### ISSUE TITLE
Statistics framework

### ISSUE THREAD

**Issue by hburn7** [osu-tournament-rating/otr-processor#9]
The Python processor sends numerous statistics to the `OtrApiClient`. The legacy processor handles stats in a...very complicated way. But in general, we need the following stats to be created and sent to the API.

Real-time stats (real-time meaning "while we are re-processing all ratings in order from oldest to newest"):
- [x] We need to know, in real-time, all of the information in the [MatchRatingStatsDTO](https://github.com/osu-tournament-rating/otr-api/blob/master/API/DTOs/MatchRatingStatsDTO.cs#L18). Tracking items like global ranking & percentile, especially the country variants, are especially tricky. To get a mapping of which players are in which country, a call to `/api/players/country-mapping` can be made (see [here](https://github.com/osu-tournament-rating/otr-api/blob/develop/API/Controllers/PlayersController.cs#L135)). This task depends on: https://github.com/osu-tournament-rating/otr-api/issues/87

Stats that can be processed after rating data is generated:
- [x] [GameWinRecords](https://github.com/osu-tournament-rating/otr-api/blob/master/API/DTOs/GameWinRecordDTO.cs)
- [x] [MatchWinRecords](https://github.com/osu-tournament-rating/otr-api/blob/master/API/DTOs/MatchWinRecordDTO.cs)
- [x] [PlayerMatchStats](https://github.com/osu-tournament-rating/otr-api/blob/master/API/DTOs/PlayerMatchStatsDTO.cs)

**Comment by hburn7** [comment]
GameWinRecord task mostly complete per #38
